### ISSUE TITLE
是否采用新 UI 框架并进行维护

### ISSUE THREAD

**Issue by langyo** [521xueweihan/advertising_law_checker#2]
我有想维护这项目的意愿，但熟悉的框架不是 Vue 而是 React……

不过，如果你能同意进行转变，我能很快地添加上新的 UI 的 XD

我准备使用的库如下：
- React
- Redux
- Material-UI

转译打包框架为 Babel + Webpack

静待你的回复

**Comment by 521xueweihan** [comment]
当然可以！

不好意思我回复晚了，我邀请你成为本项目的成员。

**Comment by 521xueweihan** [comment]
@langyo 已邀请，请开始你的表演：https://github.com/521xueweihan/advertising_law_checker/invitations

**Comment by langyo** [comment]
> @langyo 已邀请，请开始你的表演：https://github.com/521xueweihan/advertising_law_checker/invitations

最近几天我会把新 UI 合并过来的~

**Comment by langyo** [comment]
> @langyo 已邀请，请开始你的表演：https://github.com/521xueweihan/advertising_law_checker/invitations

![190f05.gif](https://miao.su/images/2019/08/13/190f05.gif)

收工，放鞭炮✌

啪啪啪啪啪啪啪啪

**Comment by 521xueweihan** [comment]
@langyo 强！你在 HG 的交流群吗？我觉得可以在群里推一下，看看用户的反馈？

**Comment by langyo** [comment]
当然可以啦
